version: '3'
services:
  # image name
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro  # sync volumes
      - /app/node_modules  # anonymous volumes
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=root
    command: npm run dev
