version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  # image name
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro  # sync volumes
      - /app/node_modules  # anonymous volumes
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=root
    command: npm run dev

  # Adding new service for mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
