version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

# Adding new service for mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    # Creat a named volume to store database...Otherwise database will be removed once we remove container
    volumes:
      - mongo-db:/data/db
  
volumes:
  mongo-db: