version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

# Adding new service for mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    # Creat a named volume to store database...Otherwise database will be removed once we remove container
    volumes:
      - mongo-db:/data/db
  
volumes:
  mongo-db: